### ISSUE TITLE
Need of private method to return CORS

### ISSUE THREAD

**Issue by ankitbko** [IdentityModel/IdentityModel.AspNet.ScopeValidation#1]
I was just going though the code and saw EmitCorsResponseHeaders method. I was just curious about the need for it as CORS can be resolved using Microsoft.AspNet.Cors middleware. I suppose having Cors and ScopeValidation middleware should not cause any issues with Options request.

BTW great work in creating middleware for this. I was tired using same RequiredScopesMiddleware class in all projects.

**Comment by leastprivilege** [comment]
Well - IIRC we had issues with CORS policy defined at the controller level and the MW blocking pre-flights.

**Comment by ankitbko** [comment]
Ok.. This seems to be working for me though I did not test it extensively for all the combinations

```
            app.UseCors(c => { c.AllowAnyHeader(); c.AllowAnyMethod(); c.AllowAnyOrigin(); });
            app.UseIISPlatformHandler();

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap = new Dictionary<string, string>();

            app.UseJwtBearerAuthentication(options =>
            {
                options.Authority = "http://localhost:44333";
                options.RequireHttpsMetadata = false;
                
                options.Audience = "http://localhost:44333/resources";
                options.AutomaticAuthenticate = true;
            });

            app.AllowScopes(new ScopeValidationOptions() { AllowedScopes = new List<string> { "api1" } });
```

**Comment by leastprivilege** [comment]
thanks for trying it!
